### PR TITLE
Add an exit option and indicate in the title that the exit mode is active.

### PR DESCRIPTION
**Pull request by Qeynos**

### CODE REVIEW

**Review by Pizzahawaiii — COMMENTED** [review]
Thanks a lot for the PR, really glad people start contributing! :rocket: 

Not sure about this one though to be hones. Two reasons:

1. I think it would be nicer to show the "Auto logout/quit enabled" message in a completely separate frame that's always in the center (or better top-center) of the screen to make it more visible. Showing it in the header makes it hard to see and remember you have it enabled. What do you think?
2. Why do we need an auto-quit option in addition to auto-logout? I think it's a bit confusing because the `setquit` only has an effect if `autologout` is enabled. Shouldn't just the auto-logout be good enough?

**Comment by Qeynos** [comment]
> Thanks a lot for the PR, really glad people start contributing! 🚀
> 
> Not sure about this one though to be hones. Two reasons:
> 
> 1. I think it would be nicer to show the "Auto logout/quit enabled" message in a completely separate frame that's always in the center (or better top-center) of the screen to make it more visible. Showing it in the header makes it hard to see and remember you have it enabled. What do you think?
> 2. Why do we need an auto-quit option in addition to auto-logout? I think it's a bit confusing because the `setquit` only has an effect if `autologout` is enabled. Shouldn't just the auto-logout be good enough?

In my routine, when there's a chance to get a world buff, I return to the main city and engage in activities like learning new skills, practicing trade skills, turning in quests, filling up rested XP, and then I leave the computer to do other things. So, I only need to know if auto-logout is enabled, hence I don't use obvious alerts.

I use the quit feature because, in some cases, I want the game to completely exit rather than stay on the login screen playing background music. At that time, I might have already taken a break and need the computer to automatically sleep after WoW closes.

There are many ways to handle exiting the game and providing alerts. The reason I mentioned the setquit solution is because my coding skills are limited, and this is the simplest method for me.

I have added the following features to the forked code:
A 10-second alert within a 60-second countdown
Interval settings for frame updates
Detection of whether the character is flying
Detection of whether the character is in the main city
These additions are based on my usage habits. Although the code may be somewhat clumsy, these changes are practical and meet my needs.

**Comment by Pizzahawaiii** [comment]
Thanks, these sound like great features. I'll consider adding some/most of them to my version if you don't mind.

I'm also happy to add an auto-exit option, I would just do it a bit differently. Maybe a `/wb exit 1` command that works independently of `/wb logout 1`.

**Comment by Pizzahawaiii** [comment]
I'm curious: why did you add the option to change the frame update interval? Why does the 1 second interval not work for you?

**Comment by Qeynos** [comment]
> Thanks, these sound like great features. I'll consider adding some/most of them to my version if you don't mind.
> 
> I'm also happy to add an auto-exit option, I would just do it a bit differently. Maybe a `/wb exit 1` command that works independently of `/wb logout 1`.



> Thanks, these sound like great features. I'll consider adding some/most of them to my version if you don't mind.
> 
> I'm also happy to add an auto-exit option, I would just do it a bit differently. Maybe a `/wb exit 1` command that works independently of `/wb logout 1`.

No problem, I forked it because I need the auto-exit feature, and my friend needs the Chinese translation. I will test it and assist with the Chinese translation.

**Comment by Qeynos** [comment]
> I'm curious: why did you add the option to change the frame update interval? Why does the 1 second interval not work for you?



> I'm curious: why did you add the option to change the frame update interval? Why does the 1 second interval not work for you?


ChatGPT
In the game, sometimes the graphics will get a little stuck, such as when taking a quest. I think the addons give too much work to the CPU, and I don't need the real-time info of the world buff. So, I tried setting the interval to 5 to reduce CPU load, but it doesn't seem very necessary.

**Pull request closed without merging**
